# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Go Hobo | Adventures for regular people.
email: gohoboco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An alternative adventure travel network, bringing together the best 
  of budget-friendly transportation, accommodation and high quality life experiences.
url: "http://localhost:4000/" # the base hostname & protocol for your site
permalink: pretty
# Build settings
kramdown:
  input: GFM

image_assets: "assets/img/"  
blog_image_assets: "/assets/img/blog/"
